// Builds artifact/dist/index.html: the water test page as ONE self-contained file (three.js and the module bundled and inlined).
//   node artifact/build.mjs            → artifact/dist/index.html
//   node artifact/build.mjs --csp      → also artifact/dist/index.csp.html (same page under a script-src without eval, for testing)
import * as esbuild from 'esbuild';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const dist = path.join(here, 'dist');
fs.mkdirSync(dist, { recursive: true });

// 1. precompile the built-in styles (so eval is optional)
const rec = path.join(dist, 'record.mjs');
await esbuild.build({ entryPoints: [path.join(here, 'record.ts')], bundle: true, platform: 'node', format: 'esm', outfile: rec, logLevel: 'error', external: [] });
const pairs = JSON.parse(execFileSync('node', [rec], { cwd: root, maxBuffer: 64 * 1024 * 1024 }).toString());
const seen = new Set();
let gen = '// @ts-nocheck\n// generated by artifact/build.mjs — do not edit\nexport const PRECOMPILED = {\n';
for (const [arg, body] of pairs) {
  const key = `${arg}\n${body}`;
  if (seen.has(key)) continue;
  seen.add(key);
  gen += `  ${JSON.stringify(key)}: function (${arg}) {\n${body}\n},\n`;
}
gen += '};\n';
fs.writeFileSync(path.join(here, 'precompiled.gen.ts'), gen);
console.log(`precompiled ${seen.size} style factories`);

// 2. bundle the page script
const result = await esbuild.build({
  entryPoints: [path.join(here, 'main.ts')],
  bundle: true, minify: true, format: 'iife', target: 'es2020', write: false, legalComments: 'none',
  define: { 'process.env.NODE_ENV': '"production"' }, logLevel: 'warning',
});
const js = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
console.log(`bundle ${(js.length / 1024).toFixed(0)} kB`);

// 3. inline into the page
const tpl = fs.readFileSync(path.join(here, 'page.html'), 'utf8');
if (!tpl.includes('/*__BUNDLE__*/')) throw new Error('page.html has no /*__BUNDLE__*/ marker');
const html = tpl.replace('/*__BUNDLE__*/', () => js);
fs.writeFileSync(path.join(dist, 'index.html'), html);
console.log(`dist/index.html ${(html.length / 1024).toFixed(0)} kB`);
if (process.argv.includes('--csp')) {
  const csp = html.replace('<title>', `<meta http-equiv="Content-Security-Policy" content="script-src 'unsafe-inline'; object-src 'none'">\n<title>`);
  fs.writeFileSync(path.join(dist, 'index.csp.html'), csp);
}
