// @ts-nocheck
// generated by artifact/build.mjs — do not edit
export const PRECOMPILED = {
  "R\n\"use strict\"; let __profile;\n\n// Trampelpfad: kaum sichtbarer Pfad, unregelmässig\nconst params = {\n  width:  { type: 'float', label: 'Breite', min: 0.25, max: 0.9, step: 0.05, default: 0.45 },\n  wobble: { type: 'float', label: 'Unruhe', min: 0, max: 1, step: 0.05, default: 0.8 },\n};\n__profile = (p, R) => R.profile('Trampelpfad').rank(0)\n  .thickness(0.2).bodyMaterial('subgrade').smooth(2)\n  .center(p.width, 'path_dirt', { kind: 'path' })\n  .both(h => h.slope(0.3, -0.04, 'grass', { kind: 'verge' }).slope(0.7, -0.15, 'grass', { kind: 'verge' }))\n  .vary(({ s }) => ({\n    widthMul: 1 + 0.45 * p.wobble * R.noise1(s * 0.25),\n    offsetX: 0.4 * p.wobble * R.noise1(s * 0.09 + 31),\n  }));\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Trampelpfad: kaum sichtbarer Pfad, unregelmässig
const params = {
  width:  { type: 'float', label: 'Breite', min: 0.25, max: 0.9, step: 0.05, default: 0.45 },
  wobble: { type: 'float', label: 'Unruhe', min: 0, max: 1, step: 0.05, default: 0.8 },
};
__profile = (p, R) => R.profile('Trampelpfad').rank(0)
  .thickness(0.2).bodyMaterial('subgrade').smooth(2)
  .center(p.width, 'path_dirt', { kind: 'path' })
  .both(h => h.slope(0.3, -0.04, 'grass', { kind: 'verge' }).slope(0.7, -0.15, 'grass', { kind: 'verge' }))
  .vary(({ s }) => ({
    widthMul: 1 + 0.45 * p.wobble * R.noise1(s * 0.25),
    offsetX: 0.4 * p.wobble * R.noise1(s * 0.09 + 31),
  }));

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Wanderweg: schmaler Erdpfad, Breite und Verlauf \"wackeln\" entlang der Strecke\nconst params = {\n  width:  { type: 'float', label: 'Breite', min: 0.4, max: 1.6, step: 0.05, default: 0.8 },\n  wobble: { type: 'float', label: 'Unruhe', min: 0, max: 1, step: 0.05, default: 0.5 },\n  benches: { type: 'bool', label: 'Rastbänke', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Wanderweg').rank(0)\n    .thickness(0.3).bodyMaterial('subgrade').smooth(3)\n    .center(p.width, 'path_dirt', { kind: 'path' })\n    .both(h => h\n      .slope(0.4, -0.06, 'grass', { kind: 'verge' })\n      .slope(0.9, -0.2, 'grass', { kind: 'verge' }))\n    .vary(({ s }) => ({\n      widthMul: 1 + 0.3 * p.wobble * R.noise1(s * 0.18),\n      offsetX: 0.35 * p.wobble * R.noise1(s * 0.06 + 100),\n    }));\n  // Wegweiser: prof.scatter('sign:wanderweg:Rigi|2 h', { at: [8], offset: 0.6 })\n  if (p.benches) prof.scatter('bench', { spacing: 260, offset: 0.9, jitterAlong: 25, side: 'right', face: 'road' });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Wanderweg: schmaler Erdpfad, Breite und Verlauf "wackeln" entlang der Strecke
const params = {
  width:  { type: 'float', label: 'Breite', min: 0.4, max: 1.6, step: 0.05, default: 0.8 },
  wobble: { type: 'float', label: 'Unruhe', min: 0, max: 1, step: 0.05, default: 0.5 },
  benches: { type: 'bool', label: 'Rastbänke', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Wanderweg').rank(0)
    .thickness(0.3).bodyMaterial('subgrade').smooth(3)
    .center(p.width, 'path_dirt', { kind: 'path' })
    .both(h => h
      .slope(0.4, -0.06, 'grass', { kind: 'verge' })
      .slope(0.9, -0.2, 'grass', { kind: 'verge' }))
    .vary(({ s }) => ({
      widthMul: 1 + 0.3 * p.wobble * R.noise1(s * 0.18),
      offsetX: 0.35 * p.wobble * R.noise1(s * 0.06 + 100),
    }));
  // Wegweiser: prof.scatter('sign:wanderweg:Rigi|2 h', { at: [8], offset: 0.6 })
  if (p.benches) prof.scatter('bench', { spacing: 260, offset: 0.9, jitterAlong: 25, side: 'right', face: 'road' });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Waldweg: Erd-/Kiesweg mit Laubboden an den Rändern\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 1.2, max: 3.0, step: 0.1, default: 2.0 },\n};\n__profile = (p, R) => R.profile('Waldweg').rank(1)\n  .thickness(0.35).bodyMaterial('subgrade').smooth(5)\n  .center(Math.max(0.5, p.width - 1.0), 'gravel_fine', { kind: 'path' })\n  .both(h => h\n    .surface(0.5, 'path_dirt', { kind: 'path' })\n    .slope(0.6, -0.08, 'forest', { kind: 'verge' })\n    .slope(1.2, -0.25, 'forest', { kind: 'verge' }));\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Waldweg: Erd-/Kiesweg mit Laubboden an den Rändern
const params = {
  width: { type: 'float', label: 'Breite', min: 1.2, max: 3.0, step: 0.1, default: 2.0 },
};
__profile = (p, R) => R.profile('Waldweg').rank(1)
  .thickness(0.35).bodyMaterial('subgrade').smooth(5)
  .center(Math.max(0.5, p.width - 1.0), 'gravel_fine', { kind: 'path' })
  .both(h => h
    .surface(0.5, 'path_dirt', { kind: 'path' })
    .slope(0.6, -0.08, 'forest', { kind: 'verge' })
    .slope(1.2, -0.25, 'forest', { kind: 'verge' }));

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Fussweg (befestigt): schmaler Belag mit seitlichem Grünstreifen\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 1.0, max: 3.0, step: 0.1, default: 1.6 },\n  lamps: { type: 'bool',  label: 'Wegbeleuchtung', default: false },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Fussweg').rank(1)\n    .thickness(0.35).bodyMaterial('subgrade').smooth(6)\n    .center(p.width, 'sidewalk', { kind: 'walkable' })\n    .both(h => h\n      .step(-0.04, 'curb', { kind: 'curb' })\n      .slope(0.7, -0.05, 'grass', { kind: 'verge' })\n      .slope(1.0, -0.2, 'grass', { kind: 'verge' }));\n  if (p.lamps) prof.lamps({ asset: 'lamp_small', spacing: 30, side: 'left', offset: 0.5 });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Fussweg (befestigt): schmaler Belag mit seitlichem Grünstreifen
const params = {
  width: { type: 'float', label: 'Breite', min: 1.0, max: 3.0, step: 0.1, default: 1.6 },
  lamps: { type: 'bool',  label: 'Wegbeleuchtung', default: false },
};
__profile = (p, R) => {
  const prof = R.profile('Fussweg').rank(1)
    .thickness(0.35).bodyMaterial('subgrade').smooth(6)
    .center(p.width, 'sidewalk', { kind: 'walkable' })
    .both(h => h
      .step(-0.04, 'curb', { kind: 'curb' })
      .slope(0.7, -0.05, 'grass', { kind: 'verge' })
      .slope(1.0, -0.2, 'grass', { kind: 'verge' }));
  if (p.lamps) prof.lamps({ asset: 'lamp_small', spacing: 30, side: 'left', offset: 0.5 });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Radweg: Asphaltband mit gestrichelter Mittellinie\nconst params = {\n  width:  { type: 'float', label: 'Breite', min: 1.5, max: 4.0, step: 0.1, default: 2.4 },\n  center: { type: 'bool',  label: 'Mittellinie', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Radweg').rank(1)\n    .thickness(0.4).bodyMaterial('subgrade').smooth(8)\n    .center(p.width, 'asphalt_dark', { kind: 'lane' })\n    .both(h => h\n      .slope(0.4, -0.04, 'gravel_fine', { kind: 'verge' })\n      .slope(1.0, -0.2, 'grass', { kind: 'verge' }));\n  if (p.center) prof.markCenter({ width: 0.1, dash: 1.5, gap: 3 });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Radweg: Asphaltband mit gestrichelter Mittellinie
const params = {
  width:  { type: 'float', label: 'Breite', min: 1.5, max: 4.0, step: 0.1, default: 2.4 },
  center: { type: 'bool',  label: 'Mittellinie', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Radweg').rank(1)
    .thickness(0.4).bodyMaterial('subgrade').smooth(8)
    .center(p.width, 'asphalt_dark', { kind: 'lane' })
    .both(h => h
      .slope(0.4, -0.04, 'gravel_fine', { kind: 'verge' })
      .slope(1.0, -0.2, 'grass', { kind: 'verge' }));
  if (p.center) prof.markCenter({ width: 0.1, dash: 1.5, gap: 3 });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Holzsteg: Bohlen quer zur Gehrichtung, Holzkörper\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 0.7, max: 2.5, step: 0.1, default: 1.2 },\n};\n__profile = (p, R) => R.profile('Holzsteg').rank(0)\n  .thickness(0.3).bodyMaterial('wood').smooth(1.5)\n  .center(p.width, 'wood', { kind: 'walkable' })\n  .both(h => h.step(-0.12, 'wood', { kind: 'curb' }).slope(0.5, -0.1, 'grass', { kind: 'verge' }));\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Holzsteg: Bohlen quer zur Gehrichtung, Holzkörper
const params = {
  width: { type: 'float', label: 'Breite', min: 0.7, max: 2.5, step: 0.1, default: 1.2 },
};
__profile = (p, R) => R.profile('Holzsteg').rank(0)
  .thickness(0.3).bodyMaterial('wood').smooth(1.5)
  .center(p.width, 'wood', { kind: 'walkable' })
  .both(h => h.step(-0.12, 'wood', { kind: 'curb' }).slope(0.5, -0.1, 'grass', { kind: 'verge' }));

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Flurstrasse / Feldweg: zwei Fahrspuren (Spurrillen) mit Mittelgras\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 2.2, max: 4.5, step: 0.1, default: 3.0 },\n  grass: { type: 'bool',  label: 'Mittelgras', default: true },\n};\n__profile = (p, R) => R.profile('Flurstrasse').rank(2)\n  .thickness(0.5).bodyMaterial('subgrade').smooth(6)\n  .center(p.grass ? 0.5 : 0.01, p.grass ? 'grass' : 'gravel', { kind: 'median', core: true })\n  .both(h => h\n    .step(-0.06, 'dirt', { kind: 'rut' })\n    .surface(0.7, 'dirt', { kind: 'lane', id: 'rut' })\n    .surface(Math.max(0.1, p.width / 2 - 0.95), 'gravel', { kind: 'lane' })\n    .slope(0.6, -0.1, 'grass', { kind: 'verge' })\n    .slope(1.6, -0.35, 'grass', { kind: 'verge' }));\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Flurstrasse / Feldweg: zwei Fahrspuren (Spurrillen) mit Mittelgras
const params = {
  width: { type: 'float', label: 'Breite', min: 2.2, max: 4.5, step: 0.1, default: 3.0 },
  grass: { type: 'bool',  label: 'Mittelgras', default: true },
};
__profile = (p, R) => R.profile('Flurstrasse').rank(2)
  .thickness(0.5).bodyMaterial('subgrade').smooth(6)
  .center(p.grass ? 0.5 : 0.01, p.grass ? 'grass' : 'gravel', { kind: 'median', core: true })
  .both(h => h
    .step(-0.06, 'dirt', { kind: 'rut' })
    .surface(0.7, 'dirt', { kind: 'lane', id: 'rut' })
    .surface(Math.max(0.1, p.width / 2 - 0.95), 'gravel', { kind: 'lane' })
    .slope(0.6, -0.1, 'grass', { kind: 'verge' })
    .slope(1.6, -0.35, 'grass', { kind: 'verge' }));

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Schotterpiste: Kiesfahrbahn mit Dachprofil, seitlich Graben\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 3, max: 6.5, step: 0.1, default: 4.4 },\n  ditch: { type: 'bool',  label: 'Graben', default: true },\n};\n__profile = (p, R) => R.profile('Schotterpiste').rank(2)\n  .thickness(0.6).bodyMaterial('subgrade').smooth(8)\n  .both(h => {\n    h.surface(p.width / 2, 'gravel', { kind: 'lane', slope: -0.03 })\n     .slope(0.4, -0.05, 'gravel_fine', { kind: 'verge' });\n    if (p.ditch) h.ditch(1.2, 0.3, 'grass'); else h.slope(1.2, -0.25, 'grass', { kind: 'verge' });\n  });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Schotterpiste: Kiesfahrbahn mit Dachprofil, seitlich Graben
const params = {
  width: { type: 'float', label: 'Breite', min: 3, max: 6.5, step: 0.1, default: 4.4 },
  ditch: { type: 'bool',  label: 'Graben', default: true },
};
__profile = (p, R) => R.profile('Schotterpiste').rank(2)
  .thickness(0.6).bodyMaterial('subgrade').smooth(8)
  .both(h => {
    h.surface(p.width / 2, 'gravel', { kind: 'lane', slope: -0.03 })
     .slope(0.4, -0.05, 'gravel_fine', { kind: 'verge' });
    if (p.ditch) h.ditch(1.2, 0.3, 'grass'); else h.slope(1.2, -0.25, 'grass', { kind: 'verge' });
  });

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Waldstrasse (Forststrasse): feiner Kies, schmale Böschung\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 2.8, max: 5, step: 0.1, default: 3.6 },\n};\n__profile = (p, R) => R.profile('Waldstrasse').rank(2)\n  .thickness(0.6).bodyMaterial('subgrade').smooth(9)\n  .both(h => h\n    .surface(p.width / 2, 'gravel_fine', { kind: 'lane', slope: -0.025 })\n    .slope(0.5, -0.06, 'path_dirt', { kind: 'verge' })\n    .ditch(1.0, 0.3, 'forest'));\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Waldstrasse (Forststrasse): feiner Kies, schmale Böschung
const params = {
  width: { type: 'float', label: 'Breite', min: 2.8, max: 5, step: 0.1, default: 3.6 },
};
__profile = (p, R) => R.profile('Waldstrasse').rank(2)
  .thickness(0.6).bodyMaterial('subgrade').smooth(9)
  .both(h => h
    .surface(p.width / 2, 'gravel_fine', { kind: 'lane', slope: -0.025 })
    .slope(0.5, -0.06, 'path_dirt', { kind: 'verge' })
    .ditch(1.0, 0.3, 'forest'));

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Alp-/Güterstrasse: schmal, Kies, Steinkante\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 2.5, max: 4.5, step: 0.1, default: 3.2 },\n  guardrail: { type: 'bool', label: 'Holzleitplanke an Abstürzen', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Alpstrasse').rank(2)\n    .thickness(0.5).bodyMaterial('subgrade').smooth(7)\n    .both(h => h\n      .surface(p.width / 2, 'gravel', { kind: 'lane', slope: -0.02 })\n      .slope(0.35, -0.05, 'rock', { kind: 'verge' })\n      .slope(1.4, -0.3, 'grass', { kind: 'verge' }));\n  if (p.guardrail) prof.guardrail('both', { variant: 'wood', offset: 0.2, minDrop: 2.5, minDropBend: 1.5 });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Alp-/Güterstrasse: schmal, Kies, Steinkante
const params = {
  width: { type: 'float', label: 'Breite', min: 2.5, max: 4.5, step: 0.1, default: 3.2 },
  guardrail: { type: 'bool', label: 'Holzleitplanke an Abstürzen', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Alpstrasse').rank(2)
    .thickness(0.5).bodyMaterial('subgrade').smooth(7)
    .both(h => h
      .surface(p.width / 2, 'gravel', { kind: 'lane', slope: -0.02 })
      .slope(0.35, -0.05, 'rock', { kind: 'verge' })
      .slope(1.4, -0.3, 'grass', { kind: 'verge' }));
  if (p.guardrail) prof.guardrail('both', { variant: 'wood', offset: 0.2, minDrop: 2.5, minDropBend: 1.5 });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Gemeindestrasse: schmaler Asphalt ohne Mittellinie\nconst params = {\n  width:    { type: 'float', label: 'Fahrbahnbreite', min: 3.5, max: 7, step: 0.1, default: 5.0 },\n  shoulder: { type: 'float', label: 'Bankett', min: 0.2, max: 1.5, step: 0.1, default: 0.5 },\n  lamps:    { type: 'enum',  label: 'Strassenlaternen', options: ['keine', 'links', 'rechts', 'beidseitig'], default: 'keine' },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Gemeindestrasse').rank(3)\n    .thickness(0.7).bodyMaterial('subgrade').smooth(12)\n    .both(h => h\n      .surface(p.width / 2, 'asphalt', { kind: 'lane', slope: -0.025 })\n      .surface(p.shoulder, 'gravel_fine', { kind: 'shoulder', slope: -0.04 })\n      .ditch(1.4, 0.35, 'grass'));\n  if (p.lamps !== 'keine') prof.lamps({ asset: 'lamp_small', spacing: 38, offset: 0.6, side: { links: 'left', rechts: 'right', beidseitig: 'both' }[p.lamps], stagger: true });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Gemeindestrasse: schmaler Asphalt ohne Mittellinie
const params = {
  width:    { type: 'float', label: 'Fahrbahnbreite', min: 3.5, max: 7, step: 0.1, default: 5.0 },
  shoulder: { type: 'float', label: 'Bankett', min: 0.2, max: 1.5, step: 0.1, default: 0.5 },
  lamps:    { type: 'enum',  label: 'Strassenlaternen', options: ['keine', 'links', 'rechts', 'beidseitig'], default: 'keine' },
};
__profile = (p, R) => {
  const prof = R.profile('Gemeindestrasse').rank(3)
    .thickness(0.7).bodyMaterial('subgrade').smooth(12)
    .both(h => h
      .surface(p.width / 2, 'asphalt', { kind: 'lane', slope: -0.025 })
      .surface(p.shoulder, 'gravel_fine', { kind: 'shoulder', slope: -0.04 })
      .ditch(1.4, 0.35, 'grass'));
  if (p.lamps !== 'keine') prof.lamps({ asset: 'lamp_small', spacing: 38, offset: 0.6, side: { links: 'left', rechts: 'right', beidseitig: 'both' }[p.lamps], stagger: true });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Dorfstrasse: Pflaster, Granit-Randsteine, Trottoir\nconst params = {\n  width:    { type: 'float', label: 'Fahrbahnbreite', min: 4, max: 8, step: 0.1, default: 5.6 },\n  sidewalk: { type: 'float', label: 'Trottoir', min: 0, max: 3, step: 0.1, default: 1.6 },\n  lamps:    { type: 'bool',  label: 'Strassenlaternen', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Dorfstrasse').rank(3)\n    .thickness(0.7).bodyMaterial('subgrade').smooth(10)\n    .both(h => {\n      h.surface(p.width / 2, 'cobble', { kind: 'lane', slope: -0.02 })\n       .step(0.12, 'curb', { kind: 'curb' })\n       .surface(0.15, 'granite', { kind: 'curb' });\n      if (p.sidewalk > 0.05) h.surface(p.sidewalk, 'sidewalk', { kind: 'walkable', core: true });\n      h.slope(0.8, -0.1, 'grass', { kind: 'verge' });\n    });\n  // lamps stand on the pavement edge (negative offset = inwards from the carriageway edge)\n  if (p.lamps) prof.lamps({ asset: 'lamp_small', spacing: 32, offset: p.sidewalk > 0.05 ? -0.35 : 0.4, side: 'both', stagger: true });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Dorfstrasse: Pflaster, Granit-Randsteine, Trottoir
const params = {
  width:    { type: 'float', label: 'Fahrbahnbreite', min: 4, max: 8, step: 0.1, default: 5.6 },
  sidewalk: { type: 'float', label: 'Trottoir', min: 0, max: 3, step: 0.1, default: 1.6 },
  lamps:    { type: 'bool',  label: 'Strassenlaternen', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Dorfstrasse').rank(3)
    .thickness(0.7).bodyMaterial('subgrade').smooth(10)
    .both(h => {
      h.surface(p.width / 2, 'cobble', { kind: 'lane', slope: -0.02 })
       .step(0.12, 'curb', { kind: 'curb' })
       .surface(0.15, 'granite', { kind: 'curb' });
      if (p.sidewalk > 0.05) h.surface(p.sidewalk, 'sidewalk', { kind: 'walkable', core: true });
      h.slope(0.8, -0.1, 'grass', { kind: 'verge' });
    });
  // lamps stand on the pavement edge (negative offset = inwards from the carriageway edge)
  if (p.lamps) prof.lamps({ asset: 'lamp_small', spacing: 32, offset: p.sidewalk > 0.05 ? -0.35 : 0.4, side: 'both', stagger: true });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Quartierstrasse: Bordstein, Trottoir, einseitiges Parkfeld je Seite\nconst params = {\n  lane:     { type: 'float', label: 'Spurbreite', min: 2.5, max: 3.5, step: 0.05, default: 2.9 },\n  parking:  { type: 'float', label: 'Parkfeld', min: 0, max: 2.6, step: 0.1, default: 2.0 },\n  sidewalk: { type: 'float', label: 'Trottoir', min: 0, max: 3, step: 0.1, default: 2.0 },\n  lamps:    { type: 'bool',  label: 'Strassenlaternen', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Quartierstrasse').rank(3)\n  .thickness(0.7).bodyMaterial('subgrade').smooth(10)\n  .both(h => {\n    h.surface(p.lane, 'asphalt', { kind: 'lane', slope: -0.02 });\n    if (p.parking > 0.05) h.surface(p.parking, 'asphalt_dark', { kind: 'parking', slope: -0.015 }).edgeLine({ back: 0.05, width: 0.1, color: 'white' });\n    h.step(0.12, 'curb', { kind: 'curb' }).surface(0.15, 'granite', { kind: 'curb' });\n    if (p.sidewalk > 0.05) h.surface(p.sidewalk, 'sidewalk', { kind: 'walkable' });\n    h.slope(0.8, -0.1, 'grass', { kind: 'verge' });\n  });\n  if (p.lamps) prof.lamps({ asset: 'lamp_small', spacing: 30, offset: p.sidewalk > 0.05 ? -0.4 : 0.4, side: 'left' });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Quartierstrasse: Bordstein, Trottoir, einseitiges Parkfeld je Seite
const params = {
  lane:     { type: 'float', label: 'Spurbreite', min: 2.5, max: 3.5, step: 0.05, default: 2.9 },
  parking:  { type: 'float', label: 'Parkfeld', min: 0, max: 2.6, step: 0.1, default: 2.0 },
  sidewalk: { type: 'float', label: 'Trottoir', min: 0, max: 3, step: 0.1, default: 2.0 },
  lamps:    { type: 'bool',  label: 'Strassenlaternen', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Quartierstrasse').rank(3)
  .thickness(0.7).bodyMaterial('subgrade').smooth(10)
  .both(h => {
    h.surface(p.lane, 'asphalt', { kind: 'lane', slope: -0.02 });
    if (p.parking > 0.05) h.surface(p.parking, 'asphalt_dark', { kind: 'parking', slope: -0.015 }).edgeLine({ back: 0.05, width: 0.1, color: 'white' });
    h.step(0.12, 'curb', { kind: 'curb' }).surface(0.15, 'granite', { kind: 'curb' });
    if (p.sidewalk > 0.05) h.surface(p.sidewalk, 'sidewalk', { kind: 'walkable' });
    h.slope(0.8, -0.1, 'grass', { kind: 'verge' });
  });
  if (p.lamps) prof.lamps({ asset: 'lamp_small', spacing: 30, offset: p.sidewalk > 0.05 ? -0.4 : 0.4, side: 'left' });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Nebenstrasse: Asphalt, optionale Leitlinie\nconst params = {\n  lane:   { type: 'float', label: 'Spurbreite', min: 2.5, max: 3.5, step: 0.05, default: 2.9 },\n  center: { type: 'bool',  label: 'Leitlinie', default: false },\n  guardrail: { type: 'bool', label: 'Leitplanke an Abstürzen', default: true },\n  posts:  { type: 'bool',  label: 'Leitpfosten', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Nebenstrasse').rank(4)\n    .thickness(0.7).bodyMaterial('subgrade').smooth(14)\n    .both(h => h\n      .surface(p.lane, 'asphalt', { kind: 'lane', slope: -0.025 })\n      .surface(0.4, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })\n      .slope(0.6, -0.05, 'gravel_fine', { kind: 'verge' })\n      .ditch(1.4, 0.35, 'grass'));\n  if (p.center) prof.markCenter({ dash: 3, gap: 6 });\n  if (p.guardrail) prof.guardrail('both', { offset: 0.3 });\n  if (p.posts) prof.scatter('delineator', { spacing: 50, offset: 0.55, side: 'both' });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Nebenstrasse: Asphalt, optionale Leitlinie
const params = {
  lane:   { type: 'float', label: 'Spurbreite', min: 2.5, max: 3.5, step: 0.05, default: 2.9 },
  center: { type: 'bool',  label: 'Leitlinie', default: false },
  guardrail: { type: 'bool', label: 'Leitplanke an Abstürzen', default: true },
  posts:  { type: 'bool',  label: 'Leitpfosten', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Nebenstrasse').rank(4)
    .thickness(0.7).bodyMaterial('subgrade').smooth(14)
    .both(h => h
      .surface(p.lane, 'asphalt', { kind: 'lane', slope: -0.025 })
      .surface(0.4, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })
      .slope(0.6, -0.05, 'gravel_fine', { kind: 'verge' })
      .ditch(1.4, 0.35, 'grass'));
  if (p.center) prof.markCenter({ dash: 3, gap: 6 });
  if (p.guardrail) prof.guardrail('both', { offset: 0.3 });
  if (p.posts) prof.scatter('delineator', { spacing: 50, offset: 0.55, side: 'both' });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Hauptstrasse / Landstrasse: Dachprofil, Leit- und Randlinien, Bankett, Graben\nconst params = {\n  laneWidth: { type: 'float', label: 'Spurbreite', min: 2.5, max: 4, step: 0.05, default: 3.0 },\n  shoulder:  { type: 'float', label: 'Bankett',    min: 0.2, max: 2.5, step: 0.1, default: 0.8 },\n  crown:     { type: 'float', label: 'Quergefälle', min: 0.0, max: 0.06, step: 0.005, default: 0.025 },\n  ditch:     { type: 'bool',  label: 'Graben', default: true },\n  lines:     { type: 'bool',  label: 'Markierungen', default: true },\n  edge:      { type: 'enum',  label: 'Randlinie', options: ['solid', 'dashed'], default: 'solid' },\n  guardrail: { type: 'bool',  label: 'Leitplanke an Abstürzen', default: true },\n  posts:     { type: 'bool',  label: 'Leitpfosten', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Hauptstrasse').rank(5)\n    .thickness(0.8).bodyMaterial('subgrade').smooth(18)\n    .both(h => {\n      h.surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -p.crown, id: 'lane' });\n      if (p.lines) h.edgeLine({ back: 0.2, style: p.edge, dash: 1, gap: 1 });\n      h.surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })\n       .slope(0.8, -0.05, 'gravel', { kind: 'verge' });\n      if (p.ditch) h.ditch(1.6, 0.4, 'grass');\n      else h.slope(1.6, -0.3, 'grass', { kind: 'verge' });\n    });\n  if (p.lines) prof.markCenter({ dash: 3, gap: 9 });\n  if (p.guardrail) prof.guardrail('both', { offset: 0.3 });\n  if (p.posts) prof.scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Hauptstrasse / Landstrasse: Dachprofil, Leit- und Randlinien, Bankett, Graben
const params = {
  laneWidth: { type: 'float', label: 'Spurbreite', min: 2.5, max: 4, step: 0.05, default: 3.0 },
  shoulder:  { type: 'float', label: 'Bankett',    min: 0.2, max: 2.5, step: 0.1, default: 0.8 },
  crown:     { type: 'float', label: 'Quergefälle', min: 0.0, max: 0.06, step: 0.005, default: 0.025 },
  ditch:     { type: 'bool',  label: 'Graben', default: true },
  lines:     { type: 'bool',  label: 'Markierungen', default: true },
  edge:      { type: 'enum',  label: 'Randlinie', options: ['solid', 'dashed'], default: 'solid' },
  guardrail: { type: 'bool',  label: 'Leitplanke an Abstürzen', default: true },
  posts:     { type: 'bool',  label: 'Leitpfosten', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Hauptstrasse').rank(5)
    .thickness(0.8).bodyMaterial('subgrade').smooth(18)
    .both(h => {
      h.surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -p.crown, id: 'lane' });
      if (p.lines) h.edgeLine({ back: 0.2, style: p.edge, dash: 1, gap: 1 });
      h.surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })
       .slope(0.8, -0.05, 'gravel', { kind: 'verge' });
      if (p.ditch) h.ditch(1.6, 0.4, 'grass');
      else h.slope(1.6, -0.3, 'grass', { kind: 'verge' });
    });
  if (p.lines) prof.markCenter({ dash: 3, gap: 9 });
  if (p.guardrail) prof.guardrail('both', { offset: 0.3 });
  if (p.posts) prof.scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Kantonsstrasse: breiter, durchgehende Randlinien, gelbe Sperrlinie als Option\nconst params = {\n  laneWidth: { type: 'float', label: 'Spurbreite', min: 3, max: 4, step: 0.05, default: 3.25 },\n  shoulder:  { type: 'float', label: 'Bankett',    min: 0.3, max: 2.5, step: 0.1, default: 1.0 },\n  noOvertaking: { type: 'bool', label: 'Sperrlinie (gelb)', default: false },\n  guardrail: { type: 'bool', label: 'Leitplanke an Abstürzen', default: true },\n  posts:     { type: 'bool', label: 'Leitpfosten', default: true },\n  avenue:    { type: 'bool', label: 'Allee (Linden)', default: false },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Kantonsstrasse').rank(6)\n    .thickness(0.9).bodyMaterial('subgrade').smooth(22)\n    .both(h => h\n      .surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -0.025 })\n      .edgeLine({ back: 0.2 })\n      .surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })\n      .slope(0.8, -0.05, 'gravel', { kind: 'verge' })\n      .ditch(1.8, 0.45, 'grass'));\n  if (p.noOvertaking) prof.markCenter({ style: 'double', color: 'yellow', spacing: 0.3 });\n  else prof.markCenter({ dash: 3, gap: 9 });\n  if (p.guardrail) prof.guardrail('both', { offset: 0.3 });\n  if (p.posts) prof.scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });\n  if (p.avenue) prof.scatter('tree_linden', { spacing: 22, offset: 3.2, side: 'both', jitterAlong: 1.2, jitterLateral: 0.4, scale: [0.85, 1.2], face: 'random' });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Kantonsstrasse: breiter, durchgehende Randlinien, gelbe Sperrlinie als Option
const params = {
  laneWidth: { type: 'float', label: 'Spurbreite', min: 3, max: 4, step: 0.05, default: 3.25 },
  shoulder:  { type: 'float', label: 'Bankett',    min: 0.3, max: 2.5, step: 0.1, default: 1.0 },
  noOvertaking: { type: 'bool', label: 'Sperrlinie (gelb)', default: false },
  guardrail: { type: 'bool', label: 'Leitplanke an Abstürzen', default: true },
  posts:     { type: 'bool', label: 'Leitpfosten', default: true },
  avenue:    { type: 'bool', label: 'Allee (Linden)', default: false },
};
__profile = (p, R) => {
  const prof = R.profile('Kantonsstrasse').rank(6)
    .thickness(0.9).bodyMaterial('subgrade').smooth(22)
    .both(h => h
      .surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -0.025 })
      .edgeLine({ back: 0.2 })
      .surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })
      .slope(0.8, -0.05, 'gravel', { kind: 'verge' })
      .ditch(1.8, 0.45, 'grass'));
  if (p.noOvertaking) prof.markCenter({ style: 'double', color: 'yellow', spacing: 0.3 });
  else prof.markCenter({ dash: 3, gap: 9 });
  if (p.guardrail) prof.guardrail('both', { offset: 0.3 });
  if (p.posts) prof.scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });
  if (p.avenue) prof.scatter('tree_linden', { spacing: 22, offset: 3.2, side: 'both', jitterAlong: 1.2, jitterLateral: 0.4, scale: [0.85, 1.2], face: 'random' });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Autostrasse: einbahnig, Doppel-Leitlinie, Pannenstreifen schmal\nconst params = {\n  laneWidth: { type: 'float', label: 'Spurbreite', min: 3, max: 4, step: 0.05, default: 3.5 },\n  shoulder:  { type: 'float', label: 'Seitenstreifen', min: 0.5, max: 3, step: 0.1, default: 1.2 },\n};\n__profile = (p, R) => R.profile('Autostrasse').rank(7)\n  .thickness(1.0).bodyMaterial('subgrade').smooth(35)\n  .markCenter({ style: 'double', spacing: 0.3 })\n  .both(h => h\n    .surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -0.025 })\n    .edgeLine({ back: 0.2 })\n    .surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })\n    .slope(1.0, -0.06, 'gravel', { kind: 'verge' })\n    .ditch(2.0, 0.5, 'grass'))\n  .guardrail('both', { offset: 0.3 })\n  .scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Autostrasse: einbahnig, Doppel-Leitlinie, Pannenstreifen schmal
const params = {
  laneWidth: { type: 'float', label: 'Spurbreite', min: 3, max: 4, step: 0.05, default: 3.5 },
  shoulder:  { type: 'float', label: 'Seitenstreifen', min: 0.5, max: 3, step: 0.1, default: 1.2 },
};
__profile = (p, R) => R.profile('Autostrasse').rank(7)
  .thickness(1.0).bodyMaterial('subgrade').smooth(35)
  .markCenter({ style: 'double', spacing: 0.3 })
  .both(h => h
    .surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -0.025 })
    .edgeLine({ back: 0.2 })
    .surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })
    .slope(1.0, -0.06, 'gravel', { kind: 'verge' })
    .ditch(2.0, 0.5, 'grass'))
  .guardrail('both', { offset: 0.3 })
  .scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Autobahn: zwei Richtungsfahrbahnen mit Betonleitwand in der Mitte, je 2 Fahrstreifen + Pannenstreifen\nconst params = {\n  lanes:    { type: 'int',   label: 'Fahrstreifen je Richtung', min: 1, max: 3, default: 2 },\n  laneWidth:{ type: 'float', label: 'Spurbreite', min: 3.25, max: 4, step: 0.05, default: 3.75 },\n  shoulder: { type: 'float', label: 'Pannenstreifen', min: 0, max: 3.5, step: 0.1, default: 3.0 },\n  median:   { type: 'float', label: 'Mittelstreifen', min: 0.6, max: 4, step: 0.1, default: 1.0 },\n};\n__profile = (p, R) => R.profile('Autobahn').rank(8)\n  .thickness(1.2).bodyMaterial('subgrade').smooth(45)\n  .center(p.median, 'concrete', { y: 0.8, kind: 'barrier', core: false })\n  .both(h => {\n    h.step(-0.8, 'concrete', { kind: 'barrier', core: false }).edgeLine({ back: -0.25 });\n    for (let i = 0; i < p.lanes; i++) {\n      h.surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -0.025, id: 'lane' + i });\n      if (i < p.lanes - 1) h.edgeLine({ back: 0, style: 'dashed', dash: 6, gap: 12 });\n    }\n    h.edgeLine({ back: 0.2, width: 0.2 });\n    if (p.shoulder > 0.05) h.surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 });\n    h.slope(1.2, -0.06, 'gravel', { kind: 'verge' }).ditch(2.2, 0.5, 'grass');\n  })\n  .guardrail('both', { offset: 0.3 })\n  .scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' })\n  .scatter('km_stone', { spacing: 1000, offset: 0.9, side: 'right', face: 'road' });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Autobahn: zwei Richtungsfahrbahnen mit Betonleitwand in der Mitte, je 2 Fahrstreifen + Pannenstreifen
const params = {
  lanes:    { type: 'int',   label: 'Fahrstreifen je Richtung', min: 1, max: 3, default: 2 },
  laneWidth:{ type: 'float', label: 'Spurbreite', min: 3.25, max: 4, step: 0.05, default: 3.75 },
  shoulder: { type: 'float', label: 'Pannenstreifen', min: 0, max: 3.5, step: 0.1, default: 3.0 },
  median:   { type: 'float', label: 'Mittelstreifen', min: 0.6, max: 4, step: 0.1, default: 1.0 },
};
__profile = (p, R) => R.profile('Autobahn').rank(8)
  .thickness(1.2).bodyMaterial('subgrade').smooth(45)
  .center(p.median, 'concrete', { y: 0.8, kind: 'barrier', core: false })
  .both(h => {
    h.step(-0.8, 'concrete', { kind: 'barrier', core: false }).edgeLine({ back: -0.25 });
    for (let i = 0; i < p.lanes; i++) {
      h.surface(p.laneWidth, 'asphalt', { kind: 'lane', slope: -0.025, id: 'lane' + i });
      if (i < p.lanes - 1) h.edgeLine({ back: 0, style: 'dashed', dash: 6, gap: 12 });
    }
    h.edgeLine({ back: 0.2, width: 0.2 });
    if (p.shoulder > 0.05) h.surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 });
    h.slope(1.2, -0.06, 'gravel', { kind: 'verge' }).ditch(2.2, 0.5, 'grass');
  })
  .guardrail('both', { offset: 0.3 })
  .scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' })
  .scatter('km_stone', { spacing: 1000, offset: 0.9, side: 'right', face: 'road' });

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Auf-/Abfahrt: eine Fahrspur mit Randlinien und Seitenstreifen\nconst params = {\n  laneWidth: { type: 'float', label: 'Spurbreite', min: 3, max: 5, step: 0.1, default: 4.0 },\n  shoulder:  { type: 'float', label: 'Seitenstreifen', min: 0.3, max: 2.5, step: 0.1, default: 1.0 },\n};\n__profile = (p, R) => R.profile('Auffahrt').rank(7)\n  .thickness(1.0).bodyMaterial('subgrade').smooth(25)\n  .center(p.laneWidth, 'asphalt', { kind: 'lane' })\n  .both(h => h\n    .edgeLine({ back: 0.2 })\n    .surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })\n    .slope(1.0, -0.06, 'gravel', { kind: 'verge' })\n    .ditch(1.8, 0.4, 'grass'))\n  .guardrail('both', { offset: 0.3 })\n  .scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Auf-/Abfahrt: eine Fahrspur mit Randlinien und Seitenstreifen
const params = {
  laneWidth: { type: 'float', label: 'Spurbreite', min: 3, max: 5, step: 0.1, default: 4.0 },
  shoulder:  { type: 'float', label: 'Seitenstreifen', min: 0.3, max: 2.5, step: 0.1, default: 1.0 },
};
__profile = (p, R) => R.profile('Auffahrt').rank(7)
  .thickness(1.0).bodyMaterial('subgrade').smooth(25)
  .center(p.laneWidth, 'asphalt', { kind: 'lane' })
  .both(h => h
    .edgeLine({ back: 0.2 })
    .surface(p.shoulder, 'asphalt_worn', { kind: 'shoulder', slope: -0.04 })
    .slope(1.0, -0.06, 'gravel', { kind: 'verge' })
    .ditch(1.8, 0.4, 'grass'))
  .guardrail('both', { offset: 0.3 })
  .scatter('delineator', { spacing: 50, offset: 0.6, side: 'both' });

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "R\n\"use strict\"; let __profile;\n\n// Kreisel: einspuriger Ring (Einbahn), Bordstein zur Mittelinsel; Zufahrten haben Kein Vortritt (Rang 6 > Rang der Zufahrten)\nconst params = {\n  lane:   { type: 'float', label: 'Fahrbahnbreite', min: 3.5, max: 5.5, step: 0.1, default: 4.5 },\n  apron:  { type: 'float', label: 'Überfahrbarer Rand', min: 0, max: 2, step: 0.1, default: 0.0 },\n  lamps:  { type: 'bool',  label: 'Laternen aussen', default: true },\n};\n__profile = (p, R) => {\n  const prof = R.profile('Kreisel').rank(6)\n    .thickness(0.8).bodyMaterial('subgrade').smooth(3)\n    .both(h => {\n      h.surface(p.lane, 'asphalt', { kind: 'lane', slope: -0.02 }).edgeLine({ back: 0.12, width: 0.12, color: 'white' });\n      if (p.apron > 0.05) h.surface(p.apron, 'granite', { kind: 'shoulder', slope: -0.02 });\n      h.step(0.12, 'curb', { kind: 'curb' }).surface(0.15, 'granite', { kind: 'curb' });\n      h.slope(1.2, -0.08, 'grass', { kind: 'verge' });\n    });\n  if (p.lamps) prof.lamps({ asset: 'lamp', spacing: 28, offset: 1.0, side: 'right' });\n  return prof;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };": function (R) {
"use strict"; let __profile;

// Kreisel: einspuriger Ring (Einbahn), Bordstein zur Mittelinsel; Zufahrten haben Kein Vortritt (Rang 6 > Rang der Zufahrten)
const params = {
  lane:   { type: 'float', label: 'Fahrbahnbreite', min: 3.5, max: 5.5, step: 0.1, default: 4.5 },
  apron:  { type: 'float', label: 'Überfahrbarer Rand', min: 0, max: 2, step: 0.1, default: 0.0 },
  lamps:  { type: 'bool',  label: 'Laternen aussen', default: true },
};
__profile = (p, R) => {
  const prof = R.profile('Kreisel').rank(6)
    .thickness(0.8).bodyMaterial('subgrade').smooth(3)
    .both(h => {
      h.surface(p.lane, 'asphalt', { kind: 'lane', slope: -0.02 }).edgeLine({ back: 0.12, width: 0.12, color: 'white' });
      if (p.apron > 0.05) h.surface(p.apron, 'granite', { kind: 'shoulder', slope: -0.02 });
      h.step(0.12, 'curb', { kind: 'curb' }).surface(0.15, 'granite', { kind: 'curb' });
      h.slope(1.2, -0.08, 'grass', { kind: 'verge' });
    });
  if (p.lamps) prof.lamps({ asset: 'lamp', spacing: 28, offset: 1.0, side: 'right' });
  return prof;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __profile };
},
  "M\n\"use strict\"; let __material;\n// asphalt: see M.asphalt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.asphalt({\n  color: 0x4d4f54,\n  tileM: 2.5,\n  noise: 0.5,\n  tracks: 0.8,\n  cracks: 0.5,\n  patches: 0.5,\n  edgeDirt: 0.4,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// asphalt: see M.asphalt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.asphalt({
  color: 0x4d4f54,
  tileM: 2.5,
  noise: 0.5,
  tracks: 0.8,
  cracks: 0.5,
  patches: 0.5,
  edgeDirt: 0.4,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// asphalt: see M.asphalt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.asphalt({\n  color: 0x62645f,\n  tileM: 2.5,\n  noise: 0.6,\n  tracks: 0.4,\n  cracks: 0.8,\n  patches: 0.7,\n  edgeDirt: 0.8,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// asphalt: see M.asphalt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.asphalt({
  color: 0x62645f,
  tileM: 2.5,
  noise: 0.6,
  tracks: 0.4,
  cracks: 0.8,
  patches: 0.7,
  edgeDirt: 0.8,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// asphalt: see M.asphalt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.asphalt({\n  color: 0x35373b,\n  tileM: 2,\n  noise: 0.45,\n  tracks: 0.3,\n  cracks: 0.2,\n  patches: 0.2,\n  edgeDirt: 0.2,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// asphalt: see M.asphalt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.asphalt({
  color: 0x35373b,
  tileM: 2,
  noise: 0.45,
  tracks: 0.3,
  cracks: 0.2,
  patches: 0.2,
  edgeDirt: 0.2,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// concrete: see M.concrete(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.concrete({\n  color: 0x9b9a95,\n  tileM: 3,\n  noise: 0.5,\n  tracks: 0.4,\n  edgeDirt: 0.3,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// concrete: see M.concrete(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.concrete({
  color: 0x9b9a95,
  tileM: 3,
  noise: 0.5,
  tracks: 0.4,
  edgeDirt: 0.3,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// cobble: see M.cobble(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.cobble({\n  color: 0x7c7a76,\n  color2: 0xa09d96,\n  tileM: 0.16,\n  noise: 0.5,\n  edgeDirt: 0.5,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// cobble: see M.cobble(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.cobble({
  color: 0x7c7a76,
  color2: 0xa09d96,
  tileM: 0.16,
  noise: 0.5,
  edgeDirt: 0.5,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// stone: see M.stone(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.stone({\n  color: 0xa8a7a2,\n  color2: 0x7d7c78,\n  tileM: 1,\n  noise: 0.6,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// stone: see M.stone(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.stone({
  color: 0xa8a7a2,
  color2: 0x7d7c78,
  tileM: 1,
  noise: 0.6,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// stone: see M.stone(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.stone({\n  color: 0xaaa9a4,\n  color2: 0x84837e,\n  tileM: 1,\n  noise: 0.5,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// stone: see M.stone(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.stone({
  color: 0xaaa9a4,
  color2: 0x84837e,
  tileM: 1,
  noise: 0.5,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// concrete: see M.concrete(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.concrete({\n  color: 0xaaa8a2,\n  tileM: 1.5,\n  noise: 0.45,\n  edgeDirt: 0.5,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// concrete: see M.concrete(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.concrete({
  color: 0xaaa8a2,
  tileM: 1.5,
  noise: 0.45,
  edgeDirt: 0.5,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// gravel: see M.gravel(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.gravel({\n  color: 0x9a9588,\n  color2: 0xc4bfae,\n  tileM: 1.5,\n  noise: 0.8,\n  tracks: 0.6,\n  edgeDirt: 0.5,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// gravel: see M.gravel(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.gravel({
  color: 0x9a9588,
  color2: 0xc4bfae,
  tileM: 1.5,
  noise: 0.8,
  tracks: 0.6,
  edgeDirt: 0.5,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// gravel: see M.gravel(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.gravel({\n  color: 0xa39d8c,\n  color2: 0xcfc9b6,\n  tileM: 1,\n  noise: 0.5,\n  tracks: 0.3,\n  edgeDirt: 0.6,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// gravel: see M.gravel(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.gravel({
  color: 0xa39d8c,
  color2: 0xcfc9b6,
  tileM: 1,
  noise: 0.5,
  tracks: 0.3,
  edgeDirt: 0.6,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.dirt({\n  color: 0x7a6248,\n  color2: 0x5d4a35,\n  tileM: 2,\n  noise: 0.7,\n  tracks: 0.9,\n  edgeDirt: 0.2,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.dirt({
  color: 0x7a6248,
  color2: 0x5d4a35,
  tileM: 2,
  noise: 0.7,
  tracks: 0.9,
  edgeDirt: 0.2,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.dirt({\n  color: 0x8a7253,\n  color2: 0x6d5841,\n  tileM: 1.5,\n  noise: 0.7,\n  tracks: 0.2,\n  edgeDirt: 0.1,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.dirt({
  color: 0x8a7253,
  color2: 0x6d5841,
  tileM: 1.5,
  noise: 0.7,
  tracks: 0.2,
  edgeDirt: 0.1,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.dirt({\n  color: 0x5d4f38,\n  color2: 0x3e5a2c,\n  tileM: 1.2,\n  noise: 0.9,\n  tracks: 0.1,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.dirt({
  color: 0x5d4f38,
  color2: 0x3e5a2c,
  tileM: 1.2,
  noise: 0.9,
  tracks: 0.1,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// grass: see M.grass(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.grass({\n  color: 0x5f7f3c,\n  color2: 0x7c9a4d,\n  tileM: 3,\n  noise: 0.6,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// grass: see M.grass(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.grass({
  color: 0x5f7f3c,
  color2: 0x7c9a4d,
  tileM: 3,
  noise: 0.6,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// wood: see M.wood(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.wood({\n  color: 0x8b6a45,\n  color2: 0x6a4f33,\n  tileM: 0.14,\n  noise: 0.5,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// wood: see M.wood(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.wood({
  color: 0x8b6a45,
  color2: 0x6a4f33,
  tileM: 0.14,
  noise: 0.5,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// stone: see M.stone(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.stone({\n  color: 0x7b7a76,\n  color2: 0x5c5b57,\n  tileM: 1.5,\n  noise: 0.9,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// stone: see M.stone(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.stone({
  color: 0x7b7a76,
  color2: 0x5c5b57,
  tileM: 1.5,
  noise: 0.9,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.dirt({\n  color: 0x6b5a46,\n  color2: 0x4d3f30,\n  tileM: 2,\n  noise: 0.6,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// dirt: see M.dirt(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.dirt({
  color: 0x6b5a46,
  color2: 0x4d3f30,
  tileM: 2,
  noise: 0.6,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// paint: see M.paint(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.paint({\n  color: 0xeeeeea,\n  color2: 0x4d4f54,\n  tileM: 1,\n  noise: 0,\n  wornPaint: 0.8,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// paint: see M.paint(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.paint({
  color: 0xeeeeea,
  color2: 0x4d4f54,
  tileM: 1,
  noise: 0,
  wornPaint: 0.8,
});

;return __material;
},
  "M\n\"use strict\"; let __material;\n// paint: see M.paint(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint\n__material = (M) => M.paint({\n  color: 0xe8c424,\n  color2: 0x4d4f54,\n  tileM: 1,\n  noise: 0,\n  wornPaint: 0.8,\n});\n\n;return __material;": function (M) {
"use strict"; let __material;
// paint: see M.paint(…) options — color, color2, tileM, noise, tracks, cracks, patches, edgeDirt, wornPaint
__material = (M) => M.paint({
  color: 0xe8c424,
  color2: 0x4d4f54,
  tileM: 1,
  noise: 0,
  wornPaint: 0.8,
});

;return __material;
},
  "B\n\"use strict\"; let __bridge;\n\n// Holzsteg: Bohlenbelag auf zwei Balken, Holzgeländer (Wanderwege)\nconst params = {\n  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 3, max: 12, step: 0.5, default: 6 },\n};\n__bridge = (p, B) => B.bridge('Holzsteg')\n  .deck({ thickness: 0.25, material: 'wood' })\n  .girders({ count: 2, depth: 0.35, width: 0.25, spread: 0.85, material: 'wood' })\n  .piers({ maxSpan: p.maxSpan, shape: 'twin', width: 1.0, depth: 0.28, round: true, footing: 0, minHeight: 1.2, material: 'wood' })\n  .abutments({ depth: 1.0, wing: 0, material: 'wood' })\n  .railing('timber');\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };": function (B) {
"use strict"; let __bridge;

// Holzsteg: Bohlenbelag auf zwei Balken, Holzgeländer (Wanderwege)
const params = {
  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 3, max: 12, step: 0.5, default: 6 },
};
__bridge = (p, B) => B.bridge('Holzsteg')
  .deck({ thickness: 0.25, material: 'wood' })
  .girders({ count: 2, depth: 0.35, width: 0.25, spread: 0.85, material: 'wood' })
  .piers({ maxSpan: p.maxSpan, shape: 'twin', width: 1.0, depth: 0.28, round: true, footing: 0, minHeight: 1.2, material: 'wood' })
  .abutments({ depth: 1.0, wing: 0, material: 'wood' })
  .railing('timber');

;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };
},
  "B\n\"use strict\"; let __bridge;\n\n// Plattenbrücke: schlanke Betonplatte, kurze Spannweiten (Bach, kleine Strasse)\nconst params = {\n  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 8, max: 30, step: 1, default: 16 },\n  thickness: { type: 'float', label: 'Plattendicke', min: 0.4, max: 1.4, step: 0.05, default: 0.7 },\n};\n__bridge = (p, B) => B.bridge('Plattenbrücke')\n  .deck({ thickness: p.thickness, material: 'concrete' })\n  .piers({ maxSpan: p.maxSpan, shape: 'wall', width: 3.5, depth: 0.8, minHeight: 1.5, footing: 0.3 })\n  .abutments({ depth: 2.0, wing: 5 })\n  .railing('steel');\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };": function (B) {
"use strict"; let __bridge;

// Plattenbrücke: schlanke Betonplatte, kurze Spannweiten (Bach, kleine Strasse)
const params = {
  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 8, max: 30, step: 1, default: 16 },
  thickness: { type: 'float', label: 'Plattendicke', min: 0.4, max: 1.4, step: 0.05, default: 0.7 },
};
__bridge = (p, B) => B.bridge('Plattenbrücke')
  .deck({ thickness: p.thickness, material: 'concrete' })
  .piers({ maxSpan: p.maxSpan, shape: 'wall', width: 3.5, depth: 0.8, minHeight: 1.5, footing: 0.3 })
  .abutments({ depth: 2.0, wing: 5 })
  .railing('steel');

;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };
},
  "B\n\"use strict\"; let __bridge;\n\n// Balkenbrücke: Platte auf Längsträgern, Pfeiler mit Querriegel\nconst params = {\n  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 15, max: 60, step: 1, default: 30 },\n  girders:  { type: 'int',   label: 'Längsträger', min: 2, max: 6, default: 3 },\n  railing:  { type: 'enum',  label: 'Geländer', options: ['steel', 'parapet'], default: 'steel' },\n  lamps:    { type: 'bool',  label: 'Laternen', default: false },\n};\n__bridge = (p, B) => {\n  const b = B.bridge('Balkenbrücke')\n    .deck({ thickness: 0.45, material: 'concrete' })\n    .girders({ count: p.girders, depth: 1.1, width: 0.55, spread: 0.7 })\n    .piers({ maxSpan: p.maxSpan, shape: 'hammer', width: 1.3, depth: 1.3, capHeight: 0.8, taper: 0.15, round: true, footing: 0.5, minHeight: 3 })\n    .abutments({ depth: 2.8, wing: 7 })\n    .railing(p.railing);\n  if (p.lamps) b.lamps({ asset: 'lamp_small', spacing: 30, side: 'both' });\n  return b;\n};\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };": function (B) {
"use strict"; let __bridge;

// Balkenbrücke: Platte auf Längsträgern, Pfeiler mit Querriegel
const params = {
  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 15, max: 60, step: 1, default: 30 },
  girders:  { type: 'int',   label: 'Längsträger', min: 2, max: 6, default: 3 },
  railing:  { type: 'enum',  label: 'Geländer', options: ['steel', 'parapet'], default: 'steel' },
  lamps:    { type: 'bool',  label: 'Laternen', default: false },
};
__bridge = (p, B) => {
  const b = B.bridge('Balkenbrücke')
    .deck({ thickness: 0.45, material: 'concrete' })
    .girders({ count: p.girders, depth: 1.1, width: 0.55, spread: 0.7 })
    .piers({ maxSpan: p.maxSpan, shape: 'hammer', width: 1.3, depth: 1.3, capHeight: 0.8, taper: 0.15, round: true, footing: 0.5, minHeight: 3 })
    .abutments({ depth: 2.8, wing: 7 })
    .railing(p.railing);
  if (p.lamps) b.lamps({ asset: 'lamp_small', spacing: 30, side: 'both' });
  return b;
};

;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };
},
  "B\n\"use strict\"; let __bridge;\n\n// Viadukt: hoher Kastenträger auf schlanken Zwillingspfeilern (Autobahn, Talquerung)\nconst params = {\n  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 25, max: 100, step: 1, default: 48 },\n  box:     { type: 'float', label: 'Trägerhöhe', min: 1.2, max: 4, step: 0.1, default: 2.2 },\n};\n__bridge = (p, B) => B.bridge('Viadukt')\n  .deck({ thickness: p.box, material: 'concrete' })\n  .piers({ maxSpan: p.maxSpan, shape: 'twin', width: 1.8, depth: 2.2, taper: 0.3, cap: true, capHeight: 1.2, footing: 0.8, minHeight: 4 })\n  .abutments({ depth: 4, wing: 10 })\n  .railing('parapet');\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };": function (B) {
"use strict"; let __bridge;

// Viadukt: hoher Kastenträger auf schlanken Zwillingspfeilern (Autobahn, Talquerung)
const params = {
  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 25, max: 100, step: 1, default: 48 },
  box:     { type: 'float', label: 'Trägerhöhe', min: 1.2, max: 4, step: 0.1, default: 2.2 },
};
__bridge = (p, B) => B.bridge('Viadukt')
  .deck({ thickness: p.box, material: 'concrete' })
  .piers({ maxSpan: p.maxSpan, shape: 'twin', width: 1.8, depth: 2.2, taper: 0.3, cap: true, capHeight: 1.2, footing: 0.8, minHeight: 4 })
  .abutments({ depth: 4, wing: 10 })
  .railing('parapet');

;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };
},
  "B\n\"use strict\"; let __bridge;\n\n// Bogenbrücke: Steinbogen mit Zwickelstützen (Alpentäler)\nconst params = {\n  maxSpan:  { type: 'float', label: 'Spannweite', min: 15, max: 80, step: 1, default: 36 },\n  rise:     { type: 'float', label: 'Pfeilhöhe (Anteil)', min: 0.1, max: 0.45, step: 0.01, default: 0.25 },\n  spandrel: { type: 'enum',  label: 'Zwickel', options: ['columns', 'solid'], default: 'columns' },\n};\n__bridge = (p, B) => B.bridge('Bogenbrücke')\n  .deck({ thickness: 0.6, material: 'granite' })\n  .arch({ rise: p.rise, ribs: 2, ribWidth: 1.4, ribDepth: 1.0, spandrel: p.spandrel, spandrelSpacing: 5, spread: 0.85, material: 'granite' })\n  .piers({ maxSpan: p.maxSpan, shape: 'wall', width: 3.5, depth: 2.2, taper: 0.2, footing: 0.6, minHeight: 2, material: 'granite' })\n  .abutments({ depth: 3.5, wing: 8, material: 'granite' })\n  .railing({ type: 'parapet', height: 1.0, material: 'granite' });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };": function (B) {
"use strict"; let __bridge;

// Bogenbrücke: Steinbogen mit Zwickelstützen (Alpentäler)
const params = {
  maxSpan:  { type: 'float', label: 'Spannweite', min: 15, max: 80, step: 1, default: 36 },
  rise:     { type: 'float', label: 'Pfeilhöhe (Anteil)', min: 0.1, max: 0.45, step: 0.01, default: 0.25 },
  spandrel: { type: 'enum',  label: 'Zwickel', options: ['columns', 'solid'], default: 'columns' },
};
__bridge = (p, B) => B.bridge('Bogenbrücke')
  .deck({ thickness: 0.6, material: 'granite' })
  .arch({ rise: p.rise, ribs: 2, ribWidth: 1.4, ribDepth: 1.0, spandrel: p.spandrel, spandrelSpacing: 5, spread: 0.85, material: 'granite' })
  .piers({ maxSpan: p.maxSpan, shape: 'wall', width: 3.5, depth: 2.2, taper: 0.2, footing: 0.6, minHeight: 2, material: 'granite' })
  .abutments({ depth: 3.5, wing: 8, material: 'granite' })
  .railing({ type: 'parapet', height: 1.0, material: 'granite' });

;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };
},
  "B\n\"use strict\"; let __bridge;\n\n// Fachwerkbrücke: Stahlfachwerk beidseitig über der Fahrbahn\nconst params = {\n  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 20, max: 70, step: 1, default: 40 },\n  height:  { type: 'float', label: 'Fachwerkhöhe', min: 3, max: 9, step: 0.5, default: 5.5 },\n  panel:   { type: 'float', label: 'Feldlänge', min: 3, max: 10, step: 0.5, default: 5 },\n};\n__bridge = (p, B) => B.bridge('Fachwerkbrücke')\n  .deck({ thickness: 0.55, material: 'concrete' })\n  .truss({ height: p.height, panel: p.panel, chord: 0.35, material: 'steel_dark' })\n  .piers({ maxSpan: p.maxSpan, shape: 'column', width: 1.6, depth: 2.2, taper: 0.2, round: false, footing: 0.6, minHeight: 3 })\n  .abutments({ depth: 3, wing: 6 })\n  .railing('none');\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };": function (B) {
"use strict"; let __bridge;

// Fachwerkbrücke: Stahlfachwerk beidseitig über der Fahrbahn
const params = {
  maxSpan: { type: 'float', label: 'Max. Spannweite', min: 20, max: 70, step: 1, default: 40 },
  height:  { type: 'float', label: 'Fachwerkhöhe', min: 3, max: 9, step: 0.5, default: 5.5 },
  panel:   { type: 'float', label: 'Feldlänge', min: 3, max: 10, step: 0.5, default: 5 },
};
__bridge = (p, B) => B.bridge('Fachwerkbrücke')
  .deck({ thickness: 0.55, material: 'concrete' })
  .truss({ height: p.height, panel: p.panel, chord: 0.35, material: 'steel_dark' })
  .piers({ maxSpan: p.maxSpan, shape: 'column', width: 1.6, depth: 2.2, taper: 0.2, round: false, footing: 0.6, minHeight: 3 })
  .abutments({ depth: 3, wing: 6 })
  .railing('none');

;return { params: typeof params !== 'undefined' ? params : {}, build: __bridge };
},
  "W\n\"use strict\"; let __water;\n\n// Bach: schmal, klar, viele Steine, weisse Stromschnellen\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 1, max: 8, step: 0.1, default: 2.6 },\n  rocks: { type: 'float', label: 'Steine / 100 m', min: 0, max: 60, step: 1, default: 16 },\n};\n__water = (p, W) => W.river('Bach')\n  .size(p.width, 0.5)\n  .colors({ shallow: 0x8fd6cc, deep: 0x2f7c86, foam: 0xf6fafb })\n  .clarity(0.85)\n  .flow({ speed: 1.8, ripple: 0.7, turbulence: 0.35, streaks: 0.55 })\n  .banks({ width: 3, slope: 0.7, material: 'gravel', strip: 0.9 })\n  .rocks({ density: p.rocks, min: 0.25, max: 1.2, inWater: 0.5 })\n  .foam({ edge: 0.6, obstacles: 0.95, rapids: 0.85, fall: 1 })\n  .particles({ flecks: 1.2, size: 0.11, spray: 0.6, mist: 0.6 })\n  .fall({ spread: 0.5, poolDepth: 2.5, poolRadius: 1.0, streak: 0.8, wallSlope: 3 });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __water };": function (W) {
"use strict"; let __water;

// Bach: schmal, klar, viele Steine, weisse Stromschnellen
const params = {
  width: { type: 'float', label: 'Breite', min: 1, max: 8, step: 0.1, default: 2.6 },
  rocks: { type: 'float', label: 'Steine / 100 m', min: 0, max: 60, step: 1, default: 16 },
};
__water = (p, W) => W.river('Bach')
  .size(p.width, 0.5)
  .colors({ shallow: 0x8fd6cc, deep: 0x2f7c86, foam: 0xf6fafb })
  .clarity(0.85)
  .flow({ speed: 1.8, ripple: 0.7, turbulence: 0.35, streaks: 0.55 })
  .banks({ width: 3, slope: 0.7, material: 'gravel', strip: 0.9 })
  .rocks({ density: p.rocks, min: 0.25, max: 1.2, inWater: 0.5 })
  .foam({ edge: 0.6, obstacles: 0.95, rapids: 0.85, fall: 1 })
  .particles({ flecks: 1.2, size: 0.11, spray: 0.6, mist: 0.6 })
  .fall({ spread: 0.5, poolDepth: 2.5, poolRadius: 1.0, streak: 0.8, wallSlope: 3 });

;return { params: typeof params !== 'undefined' ? params : {}, build: __water };
},
  "W\n\"use strict\"; let __water;\n\n// Wildbach: steil, schnell, weiss, grosse Blöcke\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 2, max: 12, step: 0.1, default: 4.5 },\n  rocks: { type: 'float', label: 'Blöcke / 100 m', min: 0, max: 80, step: 1, default: 34 },\n};\n__water = (p, W) => W.river('Wildbach')\n  .size(p.width, 0.7)\n  .colors({ shallow: 0x9edad0, deep: 0x3b8a8f, foam: 0xffffff })\n  .clarity(0.7)\n  .flow({ speed: 3.4, ripple: 0.9, turbulence: 0.5, streaks: 0.8 })\n  .banks({ width: 4, slope: 0.9, material: 'gravel', strip: 1.2 })\n  .rocks({ density: p.rocks, min: 0.4, max: 2.2, inWater: 0.6, color: 0x7d7c78 })\n  .foam({ edge: 0.8, obstacles: 1, rapids: 1, fall: 1 })\n  .particles({ flecks: 2, size: 0.14, spray: 0.9, mist: 0.8 })\n  .fall({ spread: 0.7, poolDepth: 4, poolRadius: 1.1, streak: 0.95, wallSlope: 3.5 });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __water };": function (W) {
"use strict"; let __water;

// Wildbach: steil, schnell, weiss, grosse Blöcke
const params = {
  width: { type: 'float', label: 'Breite', min: 2, max: 12, step: 0.1, default: 4.5 },
  rocks: { type: 'float', label: 'Blöcke / 100 m', min: 0, max: 80, step: 1, default: 34 },
};
__water = (p, W) => W.river('Wildbach')
  .size(p.width, 0.7)
  .colors({ shallow: 0x9edad0, deep: 0x3b8a8f, foam: 0xffffff })
  .clarity(0.7)
  .flow({ speed: 3.4, ripple: 0.9, turbulence: 0.5, streaks: 0.8 })
  .banks({ width: 4, slope: 0.9, material: 'gravel', strip: 1.2 })
  .rocks({ density: p.rocks, min: 0.4, max: 2.2, inWater: 0.6, color: 0x7d7c78 })
  .foam({ edge: 0.8, obstacles: 1, rapids: 1, fall: 1 })
  .particles({ flecks: 2, size: 0.14, spray: 0.9, mist: 0.8 })
  .fall({ spread: 0.7, poolDepth: 4, poolRadius: 1.1, streak: 0.95, wallSlope: 3.5 });

;return { params: typeof params !== 'undefined' ? params : {}, build: __water };
},
  "W\n\"use strict\"; let __water;\n\n// Fluss: breit, ruhig, grünlich\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 6, max: 40, step: 0.5, default: 14 },\n};\n__water = (p, W) => W.river('Fluss')\n  .size(p.width, 2.4)\n  .colors({ shallow: 0x8fbfa8, deep: 0x1d4a4f, foam: 0xf2f6f4 })\n  .clarity(0.45)\n  .flow({ speed: 1.3, ripple: 0.5, turbulence: 0.1, streaks: 0.4 })\n  .banks({ width: 7, slope: 0.35, material: 'gravel_fine', strip: 2.5 })\n  .rocks({ density: 5, min: 0.3, max: 1.4, inWater: 0.35 })\n  .foam({ edge: 0.35, obstacles: 0.7, rapids: 0.7, fall: 1 })\n  .particles({ flecks: 0.7, size: 0.16, spray: 0.4, mist: 0.5 })\n  .fall({ spread: 0.4, poolDepth: 5, poolRadius: 0.8, streak: 0.7, wallSlope: 1.4 });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __water };": function (W) {
"use strict"; let __water;

// Fluss: breit, ruhig, grünlich
const params = {
  width: { type: 'float', label: 'Breite', min: 6, max: 40, step: 0.5, default: 14 },
};
__water = (p, W) => W.river('Fluss')
  .size(p.width, 2.4)
  .colors({ shallow: 0x8fbfa8, deep: 0x1d4a4f, foam: 0xf2f6f4 })
  .clarity(0.45)
  .flow({ speed: 1.3, ripple: 0.5, turbulence: 0.1, streaks: 0.4 })
  .banks({ width: 7, slope: 0.35, material: 'gravel_fine', strip: 2.5 })
  .rocks({ density: 5, min: 0.3, max: 1.4, inWater: 0.35 })
  .foam({ edge: 0.35, obstacles: 0.7, rapids: 0.7, fall: 1 })
  .particles({ flecks: 0.7, size: 0.16, spray: 0.4, mist: 0.5 })
  .fall({ spread: 0.4, poolDepth: 5, poolRadius: 0.8, streak: 0.7, wallSlope: 1.4 });

;return { params: typeof params !== 'undefined' ? params : {}, build: __water };
},
  "W\n\"use strict\"; let __water;\n\n// Strom: sehr breit, träge, trüb\nconst params = {\n  width: { type: 'float', label: 'Breite', min: 20, max: 120, step: 1, default: 40 },\n};\n__water = (p, W) => W.river('Strom')\n  .size(p.width, 5)\n  .colors({ shallow: 0x8a9c7a, deep: 0x26403a, foam: 0xeeeeea })\n  .clarity(0.25)\n  .flow({ speed: 1.0, ripple: 0.35, turbulence: 0.05, streaks: 0.3 })\n  .banks({ width: 12, slope: 0.25, material: 'gravel_fine', strip: 4 })\n  .rocks({ density: 2, min: 0.4, max: 1.6, inWater: 0.2 })\n  .foam({ edge: 0.25, obstacles: 0.6, rapids: 0.6, fall: 1 })\n  .particles({ flecks: 0.4, size: 0.22, spray: 0.3, mist: 0.4 })\n  .fall({ spread: 0.3, poolDepth: 8, poolRadius: 0.7, streak: 0.6, wallSlope: 1.2 });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __water };": function (W) {
"use strict"; let __water;

// Strom: sehr breit, träge, trüb
const params = {
  width: { type: 'float', label: 'Breite', min: 20, max: 120, step: 1, default: 40 },
};
__water = (p, W) => W.river('Strom')
  .size(p.width, 5)
  .colors({ shallow: 0x8a9c7a, deep: 0x26403a, foam: 0xeeeeea })
  .clarity(0.25)
  .flow({ speed: 1.0, ripple: 0.35, turbulence: 0.05, streaks: 0.3 })
  .banks({ width: 12, slope: 0.25, material: 'gravel_fine', strip: 4 })
  .rocks({ density: 2, min: 0.4, max: 1.6, inWater: 0.2 })
  .foam({ edge: 0.25, obstacles: 0.6, rapids: 0.6, fall: 1 })
  .particles({ flecks: 0.4, size: 0.22, spray: 0.3, mist: 0.4 })
  .fall({ spread: 0.3, poolDepth: 8, poolRadius: 0.7, streak: 0.6, wallSlope: 1.2 });

;return { params: typeof params !== 'undefined' ? params : {}, build: __water };
},
  "W\n\"use strict\"; let __water;\n\n// Bergsee: klares Türkis, steinige Ufer\nconst params = {\n  waves: { type: 'float', label: 'Wellen', min: 0, max: 0.4, step: 0.01, default: 0.05 },\n};\n__water = (p, W) => W.lake('Bergsee')\n  .size(10, 9)\n  .colors({ shallow: 0x86e6d8, deep: 0x0d4766, foam: 0xf6fafb })\n  .clarity(0.9)\n  .waves({ height: p.waves, scale: 9, speed: 0.6 })\n  .flow({ ripple: 0.3 })\n  .banks({ width: 7, slope: 0.4, material: 'gravel', strip: 2 })\n  .rocks({ density: 7, min: 0.3, max: 1.6, inWater: 0.35 })\n  .foam({ edge: 0.5, obstacles: 0.8, rapids: 0, fall: 1 })\n  .particles({ flecks: 0.15, size: 0.1, spray: 0.2, mist: 0.2 });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __water };": function (W) {
"use strict"; let __water;

// Bergsee: klares Türkis, steinige Ufer
const params = {
  waves: { type: 'float', label: 'Wellen', min: 0, max: 0.4, step: 0.01, default: 0.05 },
};
__water = (p, W) => W.lake('Bergsee')
  .size(10, 9)
  .colors({ shallow: 0x86e6d8, deep: 0x0d4766, foam: 0xf6fafb })
  .clarity(0.9)
  .waves({ height: p.waves, scale: 9, speed: 0.6 })
  .flow({ ripple: 0.3 })
  .banks({ width: 7, slope: 0.4, material: 'gravel', strip: 2 })
  .rocks({ density: 7, min: 0.3, max: 1.6, inWater: 0.35 })
  .foam({ edge: 0.5, obstacles: 0.8, rapids: 0, fall: 1 })
  .particles({ flecks: 0.15, size: 0.1, spray: 0.2, mist: 0.2 });

;return { params: typeof params !== 'undefined' ? params : {}, build: __water };
},
  "W\n\"use strict\"; let __water;\n\n// Gletschersee: milchig-türkis, trüb, kalt\n__water = (p, W) => W.lake('Gletschersee')\n  .size(10, 14)\n  .colors({ shallow: 0xa6ece0, deep: 0x2a8fa6, foam: 0xffffff })\n  .clarity(0.18)\n  .waves({ height: 0.03, scale: 12, speed: 0.4 })\n  .banks({ width: 8, slope: 0.3, material: 'gravel_fine', strip: 3 })\n  .rocks({ density: 4, min: 0.3, max: 1.8, inWater: 0.25, color: 0xa09d96 })\n  .foam({ edge: 0.35, obstacles: 0.6, rapids: 0, fall: 1 });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __water };": function (W) {
"use strict"; let __water;

// Gletschersee: milchig-türkis, trüb, kalt
__water = (p, W) => W.lake('Gletschersee')
  .size(10, 14)
  .colors({ shallow: 0xa6ece0, deep: 0x2a8fa6, foam: 0xffffff })
  .clarity(0.18)
  .waves({ height: 0.03, scale: 12, speed: 0.4 })
  .banks({ width: 8, slope: 0.3, material: 'gravel_fine', strip: 3 })
  .rocks({ density: 4, min: 0.3, max: 1.8, inWater: 0.25, color: 0xa09d96 })
  .foam({ edge: 0.35, obstacles: 0.6, rapids: 0, fall: 1 });

;return { params: typeof params !== 'undefined' ? params : {}, build: __water };
},
  "W\n\"use strict\"; let __water;\n\n// Weiher: flach, grün-braun, ruhig\n__water = (p, W) => W.lake('Weiher')\n  .size(10, 2.2)\n  .colors({ shallow: 0x8aa078, deep: 0x2f4a38, foam: 0xe8ede4 })\n  .clarity(0.3)\n  .waves({ height: 0.02, scale: 5, speed: 0.3 })\n  .banks({ width: 5, slope: 0.25, material: 'gravel_fine', strip: 2 })\n  .rocks({ density: 3, min: 0.2, max: 0.9, inWater: 0.2 })\n  .foam({ edge: 0.2, obstacles: 0.5, rapids: 0, fall: 1 })\n  .particles({ flecks: 0.2, size: 0.16, spray: 0, mist: 0 });\n\n;return { params: typeof params !== 'undefined' ? params : {}, build: __water };": function (W) {
"use strict"; let __water;

// Weiher: flach, grün-braun, ruhig
__water = (p, W) => W.lake('Weiher')
  .size(10, 2.2)
  .colors({ shallow: 0x8aa078, deep: 0x2f4a38, foam: 0xe8ede4 })
  .clarity(0.3)
  .waves({ height: 0.02, scale: 5, speed: 0.3 })
  .banks({ width: 5, slope: 0.25, material: 'gravel_fine', strip: 2 })
  .rocks({ density: 3, min: 0.2, max: 0.9, inWater: 0.2 })
  .foam({ edge: 0.2, obstacles: 0.5, rapids: 0, fall: 1 })
  .particles({ flecks: 0.2, size: 0.16, spray: 0, mist: 0 });

;return { params: typeof params !== 'undefined' ? params : {}, build: __water };
},
};
